import type {
  CacheStorageSettings,
  ColumnVisibility,
  DailyRollupSettings,
  FeedConfig,
  OsvFeedConfig,
  SyncControls,
  VulnDashSettings
} from './types';
import { BUILT_IN_FEEDS, FEED_TYPES } from '../../domain/feeds/FeedTypes';
import { CLOSED_TRIAGE_STATES } from '../../domain/triage/TriageState';

export const DEFAULT_COLUMN_VISIBILITY: ColumnVisibility = {
  id: true,
  title: true,
  source: true,
  severity: true,
  cvssScore: true,
  publishedAt: true
};

export const DEFAULT_OSV_ENDPOINT_URL = 'https://api.osv.dev/v1/querybatch';
export const DEFAULT_OSV_MAX_BATCH_SIZE = 1000;
export const MAX_CONFIGURABLE_OSV_BATCH_SIZE = 10_000;

export const DEFAULT_FEEDS: FeedConfig[] = [
  {
    id: BUILT_IN_FEEDS.NVD.id,
    name: BUILT_IN_FEEDS.NVD.name,
    type: BUILT_IN_FEEDS.NVD.type,
    enabled: true,
    dateFilterType: 'modified'
  },
  {
    id: BUILT_IN_FEEDS.GITHUB_ADVISORY.id,
    name: BUILT_IN_FEEDS.GITHUB_ADVISORY.name,
    type: BUILT_IN_FEEDS.GITHUB_ADVISORY.type,
    enabled: true
  },
  {
    id: BUILT_IN_FEEDS.OSV.id,
    name: BUILT_IN_FEEDS.OSV.name,
    type: BUILT_IN_FEEDS.OSV.type,
    enabled: false,
    cacheTtlMs: 6 * 60 * 60 * 1000,
    negativeCacheTtlMs: 60 * 60 * 1000,
    requestTimeoutMs: 15_000,
    maxConcurrentBatches: 4,
    osvEndpointUrl: DEFAULT_OSV_ENDPOINT_URL,
    osvMaxBatchSize: DEFAULT_OSV_MAX_BATCH_SIZE
  }
];

export const MAX_OSV_CONCURRENT_BATCHES = 8;

export const DEFAULT_CACHE_STORAGE: CacheStorageSettings = {
  hardCap: 5000,
  hydrateMaxItems: 1000,
  hydratePageSize: 200,
  pruneBatchSize: 250,
  ttlMs: 30 * 24 * 60 * 60 * 1000
};

export const DEFAULT_DAILY_ROLLUP_SETTINGS: DailyRollupSettings = {
  folderPath: 'VulnDash Briefings',
  severityThreshold: 'HIGH',
  excludedTriageStates: [...CLOSED_TRIAGE_STATES],
  includeUnmappedFindings: true,
  autoGenerateOnFirstSyncOfDay: false,
  lastAutoGeneratedOn: ''
};

export const DEFAULT_SYNC_CONTROLS: SyncControls = {
  maxPages: 10,
  maxItems: 500,
  retryCount: 3,
  backoffBaseMs: 1_000,
  overlapWindowMs: 180_000,
  bootstrapLookbackMs: 86_400_000,
  debugHttpMetadata: false
};

export const SETTINGS_VERSION = 10;

export const DEFAULT_SETTINGS: VulnDashSettings = {
  pollingIntervalMs: 60_000,
  pollOnStartup: true,
  keywordFilters: [],
  manualProductFilters: [],
  sbomFolders: [],
  followedSbomComponentKeys: [],
  disabledSbomComponentKeys: [],
  productFilters: [],
  minSeverity: 'MEDIUM',
  minCvssScore: 4.0,
  nvdApiKey: '',
  githubToken: '',
  systemNotificationsEnabled: true,
  desktopAlertsHighOrCritical: false,
  cacheDurationMs: 60_000,
  maxResults: 200,
  defaultSortOrder: 'publishedAt',
  dashboardDateField: 'modified',
  colorCodedSeverity: true,
  columnVisibility: DEFAULT_COLUMN_VISIBILITY,
  triageFilter: 'all',
  keywordRegexEnabled: false,
  enableNvdFeed: true,
  enableGithubFeed: true,
  dailyRollup: { ...DEFAULT_DAILY_ROLLUP_SETTINGS },
  sboms: [],
  sbomOverrides: {},
  sbomImportMode: 'append',
  sbomPath: '',
  syncControls: { ...DEFAULT_SYNC_CONTROLS },
  sourceSyncCursor: {},
  cacheStorage: DEFAULT_CACHE_STORAGE,
  settingsVersion: SETTINGS_VERSION,
  feeds: DEFAULT_FEEDS.map((feed) => ({ ...feed }))
};

export const getDefaultOsvFeedConfig = (): OsvFeedConfig => {
  const defaultFeed = DEFAULT_FEEDS.find((feed): feed is OsvFeedConfig => feed.type === FEED_TYPES.OSV);
  if (!defaultFeed) {
    throw new Error('Missing default OSV feed configuration.');
  }

  return defaultFeed;
};

export const normalizeOsvEndpointUrl = (value: unknown, fallback = DEFAULT_OSV_ENDPOINT_URL): string => {
  const candidate = typeof value === 'string' ? value.trim() : '';
  if (!candidate) {
    return fallback;
  }

  try {
    const parsed = new URL(candidate);
    if (parsed.protocol !== 'http:' && parsed.protocol !== 'https:') {
      return fallback;
    }

    return parsed.toString();
  } catch {
    return fallback;
  }
};

export const parseConfiguredOsvEndpointUrl = (value: string): string | null => {
  const normalized = normalizeOsvEndpointUrl(value, '');
  return normalized.length > 0 ? normalized : null;
};

export const normalizeOsvMaxBatchSize = (
  value: unknown,
  fallback = DEFAULT_OSV_MAX_BATCH_SIZE
): number => {
  if (typeof value !== 'number' || !Number.isFinite(value)) {
    return fallback;
  }

  const normalized = Math.floor(value);
  if (normalized < 1 || normalized > MAX_CONFIGURABLE_OSV_BATCH_SIZE) {
    return fallback;
  }

  return normalized;
};

export const parseConfiguredOsvMaxBatchSize = (value: string): number | null => {
  const trimmed = value.trim();
  if (!/^\d+$/.test(trimmed)) {
    return null;
  }

  const normalized = normalizeOsvMaxBatchSize(Number.parseInt(trimmed, 10), 0);
  return normalized > 0 ? normalized : null;
};
