import type {
  CacheStorageSettings,
  ColumnVisibility,
  DailyRollupSettings,
  FeedConfig,
  OsvFeedConfig,
  SyncControls,
  VulnDashSettings
} from './types';
import { BUILT_IN_FEEDS, FEED_TYPES } from '../../domain/feeds/FeedTypes';
import { CLOSED_TRIAGE_STATES } from '../../domain/triage/TriageState';

export const DEFAULT_COLUMN_VISIBILITY: ColumnVisibility = {
  id: true,
  title: true,
  source: true,
  severity: true,
  cvssScore: true,
  publishedAt: true
};

export const DEFAULT_FEEDS: FeedConfig[] = [
  {
    id: BUILT_IN_FEEDS.NVD.id,
    name: BUILT_IN_FEEDS.NVD.name,
    type: BUILT_IN_FEEDS.NVD.type,
    enabled: true,
    dateFilterType: 'modified'
  },
  {
    id: BUILT_IN_FEEDS.GITHUB_ADVISORY.id,
    name: BUILT_IN_FEEDS.GITHUB_ADVISORY.name,
    type: BUILT_IN_FEEDS.GITHUB_ADVISORY.type,
    enabled: true
  },
  {
    id: BUILT_IN_FEEDS.OSV.id,
    name: BUILT_IN_FEEDS.OSV.name,
    type: BUILT_IN_FEEDS.OSV.type,
    enabled: false,
    cacheTtlMs: 6 * 60 * 60 * 1000,
    negativeCacheTtlMs: 60 * 60 * 1000,
    requestTimeoutMs: 15_000,
    maxConcurrentBatches: 4
  }
];

export const MAX_OSV_CONCURRENT_BATCHES = 8;

export const DEFAULT_CACHE_STORAGE: CacheStorageSettings = {
  hardCap: 5000,
  hydrateMaxItems: 1000,
  hydratePageSize: 200,
  pruneBatchSize: 250,
  ttlMs: 30 * 24 * 60 * 60 * 1000
};

export const DEFAULT_DAILY_ROLLUP_SETTINGS: DailyRollupSettings = {
  folderPath: 'VulnDash Briefings',
  severityThreshold: 'HIGH',
  excludedTriageStates: [...CLOSED_TRIAGE_STATES],
  includeUnmappedFindings: true,
  autoGenerateOnFirstSyncOfDay: false,
  lastAutoGeneratedOn: ''
};

export const DEFAULT_SYNC_CONTROLS: SyncControls = {
  maxPages: 10,
  maxItems: 500,
  retryCount: 3,
  backoffBaseMs: 1_000,
  overlapWindowMs: 180_000,
  bootstrapLookbackMs: 86_400_000,
  debugHttpMetadata: false
};

export const SETTINGS_VERSION = 9;

export const DEFAULT_SETTINGS: VulnDashSettings = {
  pollingIntervalMs: 60_000,
  pollOnStartup: true,
  keywordFilters: [],
  manualProductFilters: [],
  sbomFolders: [],
  followedSbomComponentKeys: [],
  disabledSbomComponentKeys: [],
  productFilters: [],
  minSeverity: 'MEDIUM',
  minCvssScore: 4.0,
  nvdApiKey: '',
  githubToken: '',
  systemNotificationsEnabled: true,
  desktopAlertsHighOrCritical: false,
  cacheDurationMs: 60_000,
  maxResults: 200,
  defaultSortOrder: 'publishedAt',
  dashboardDateField: 'modified',
  colorCodedSeverity: true,
  columnVisibility: DEFAULT_COLUMN_VISIBILITY,
  triageFilter: 'all',
  keywordRegexEnabled: false,
  enableNvdFeed: true,
  enableGithubFeed: true,
  dailyRollup: { ...DEFAULT_DAILY_ROLLUP_SETTINGS },
  sboms: [],
  sbomOverrides: {},
  sbomImportMode: 'append',
  sbomPath: '',
  syncControls: { ...DEFAULT_SYNC_CONTROLS },
  sourceSyncCursor: {},
  cacheStorage: DEFAULT_CACHE_STORAGE,
  settingsVersion: SETTINGS_VERSION,
  feeds: DEFAULT_FEEDS.map((feed) => ({ ...feed }))
};

export const getDefaultOsvFeedConfig = (): OsvFeedConfig => {
  const defaultFeed = DEFAULT_FEEDS.find((feed): feed is OsvFeedConfig => feed.type === FEED_TYPES.OSV);
  if (!defaultFeed) {
    throw new Error('Missing default OSV feed configuration.');
  }

  return defaultFeed;
};
