import { FEED_TYPES, type FeedType } from '../../domain/feeds/FeedTypes';
import type { Severity } from '../../domain/value-objects/Severity';
import type { NormalizedSbomDocument } from '../../domain/sbom/types';
import type { TriageFilterMode } from '../triage/FilterByTriageState';
import type { TriageState } from '../../domain/triage/TriageState';

export type DashboardSortOrder = 'publishedAt' | 'cvssScore';
export type DashboardDateField = 'published' | 'modified';
export type DashboardDateRangePreset = 'past_day' | 'past_3_days' | 'past_7_days' | 'custom';



export interface ColumnVisibility {
  id: boolean;
  title: boolean;
  source: boolean;
  severity: boolean;
  cvssScore: boolean;
  publishedAt: boolean;
}

export interface SyncControls {
  maxPages: number;
  maxItems: number;
  retryCount: number;
  backoffBaseMs: number;
  overlapWindowMs: number;
  bootstrapLookbackMs: number;
  debugHttpMetadata: boolean;
}

export interface CacheStorageSettings {
  hardCap: number;
  hydrateMaxItems: number;
  hydratePageSize: number;
  pruneBatchSize: number;
  ttlMs: number;
}

export interface DailyRollupSettings {
  folderPath: string;
  severityThreshold: Severity;
  excludedTriageStates: TriageState[];
  includeUnmappedFindings: boolean;
  autoGenerateOnFirstSyncOfDay: boolean;
  lastAutoGeneratedOn: string;
}

export type FeedConfigType = FeedType;

interface FeedConfigBase {
  id: string;
  name: string;
  enabled: boolean;
  token?: string;
}

export interface NvdFeedConfig extends FeedConfigBase {
  type: typeof FEED_TYPES.NVD;
  apiKey?: string;
  dateFilterType?: 'published' | 'modified';
}

export interface GitHubAdvisoryFeedConfig extends FeedConfigBase {
  type: typeof FEED_TYPES.GITHUB_ADVISORY;
}

export interface GitHubRepoFeedConfig extends FeedConfigBase {
  type: typeof FEED_TYPES.GITHUB_REPO;
  repoPath: string;
}

export interface GenericJsonFeedConfig extends FeedConfigBase {
  type: typeof FEED_TYPES.GENERIC_JSON;
  url: string;
  authHeaderName?: string;
}

export interface OsvFeedConfig extends FeedConfigBase {
  readonly type: typeof FEED_TYPES.OSV;
  readonly cacheTtlMs: number;
  readonly negativeCacheTtlMs: number;
  readonly requestTimeoutMs: number;
  readonly maxConcurrentBatches: number;
}

export type FeedConfig =
  | NvdFeedConfig
  | GitHubAdvisoryFeedConfig
  | GitHubRepoFeedConfig
  | GenericJsonFeedConfig
  | OsvFeedConfig;

export interface SbomComponentOverride {
  excluded?: boolean;
  editedName?: string;
}

export interface ImportedSbomConfig {
  id: string;
  label: string;
  path: string;
  enabled: boolean;
  lastImportedAt: number;
  contentHash: string;
  namespace?: string;
  componentCount?: number;
  lastError?: string;
  linkedProjectNotePath?: string;
  linkedProjectDisplayName?: string;
}

export interface RuntimeSbomComponent {
  normalizedName: string;
  originalName: string;
}

export interface RuntimeSbomState {
  components: RuntimeSbomComponent[];
  document: NormalizedSbomDocument;
  hash: string;
  lastError: string | null;
  lastLoadedAt: number;
  sourcePath: string;
}

export interface VulnDashSettings {
  pollingIntervalMs: number;
  pollOnStartup: boolean;
  keywordFilters: string[];
  manualProductFilters: string[];
  sbomFolders: string[];
  followedSbomComponentKeys: string[];
  disabledSbomComponentKeys: string[];
  /**
   * Computed output only. Manual edits must target `manualProductFilters`.
   */
  productFilters: string[];
  minSeverity: Severity;
  minCvssScore: number;
  nvdApiKey: string;
  githubToken: string;
  systemNotificationsEnabled: boolean;
  desktopAlertsHighOrCritical: boolean;
  cacheDurationMs: number;
  maxResults: number;
  defaultSortOrder: DashboardSortOrder;
  dashboardDateField: DashboardDateField;
  colorCodedSeverity: boolean;
  columnVisibility: ColumnVisibility;
  triageFilter: TriageFilterMode;
  keywordRegexEnabled: boolean;
  enableNvdFeed: boolean;
  enableGithubFeed: boolean;
  dailyRollup: DailyRollupSettings;
  sboms: ImportedSbomConfig[];
  sbomOverrides: Record<string, SbomComponentOverride>;
  sbomImportMode: 'replace' | 'append';
  /**
   * Legacy-only migration field. New logic must rely on `sboms`.
   */
  sbomPath: string;
  syncControls: SyncControls;
  sourceSyncCursor: Record<string, string>;
  cacheStorage: CacheStorageSettings;
  settingsVersion: number;
  feeds: FeedConfig[];
}

export interface ResolvedSbomComponent {
  displayName: string;
  editedName?: string;
  excluded: boolean;
  normalizedName: string;
  originalName: string;
}

export const buildSbomOverrideKey = (sbomId: string, originalName: string): string =>
  `${sbomId}::${originalName.trim()}`;
