import assert from 'node:assert/strict';
import test from 'node:test';
import { DailyRollupGenerator, type DailyRollupWriter } from '../../../src/application/rollup/DailyRollupGenerator';
import type { RenderedDailyRollup } from '../../../src/application/rollup/RollupMarkdownRenderer';
import type { RollupFinding } from '../../../src/domain/rollup/RollupFinding';
import type { DailyRollupSettings } from '../../../src/application/use-cases/types';
import type { SelectRollupFindings } from '../../../src/application/rollup/SelectRollupFindings';
import type { RollupMarkdownRenderer } from '../../../src/application/rollup/RollupMarkdownRenderer';

const settings: DailyRollupSettings = {
  autoGenerateOnFirstSyncOfDay: false,
  excludedTriageStates: ['mitigated', 'false_positive', 'suppressed'],
  folderPath: 'VulnDash Briefings',
  includeUnmappedFindings: true,
  lastAutoGeneratedOn: '',
  severityThreshold: 'HIGH'
};

test('DailyRollupGenerator orchestrates selection, rendering, and writing', async () => {
  const findings: RollupFinding[] = [];
  const calls: string[] = [];
  const selector = {
    execute: (input: { readonly date?: string; }) => {
      calls.push('select');
      assert.equal(input.date, undefined);
      return findings;
    }
  } as unknown as SelectRollupFindings;
  const rendered: RenderedDailyRollup = {
    analystNotesHeading: '## Analyst Notes',
    analystNotesPlaceholder: '- Placeholder',
    managedSections: [],
    title: '# VulnDash Briefing 2026-04-18'
  };
  const renderer = {
    render: (input: { readonly date: string; readonly findings: readonly RollupFinding[]; }) => {
      calls.push('render');
      assert.equal(input.date, '2026-04-18');
      assert.equal(input.findings, findings);
      return rendered;
    }
  } as unknown as RollupMarkdownRenderer;
  const writer: DailyRollupWriter = {
    write: async (input) => {
      calls.push('write');
      assert.equal(input.date, '2026-04-18');
      assert.equal(input.document, rendered);
      assert.equal(input.folderPath, 'VulnDash Briefings');
      return {
        content: '# VulnDash Briefing 2026-04-18',
        created: true,
        path: 'VulnDash Briefings/VulnDash Briefing 2026-04-18.md'
      };
    }
  };

  const result = await new DailyRollupGenerator(selector, renderer, writer).execute({
    affectedProjectsByVulnerabilityRef: new Map(),
    date: '2026-04-18',
    settings,
    triageByCacheKey: new Map(),
    vulnerabilities: []
  });

  assert.deepEqual(calls, ['select', 'render', 'write']);
  assert.equal(result.findingsCount, 0);
  assert.equal(result.path, 'VulnDash Briefings/VulnDash Briefing 2026-04-18.md');
});
