// tests/application/rollup/DailyRollupGenerator.test.ts
import assert from "node:assert/strict";
import test from "node:test";

// src/domain/value-objects/Severity.ts
var severityOrder = {
  NONE: 0,
  LOW: 1,
  MEDIUM: 2,
  HIGH: 3,
  CRITICAL: 4
};

// src/domain/rollup/DailyRollupPolicy.ts
var DailyRollupPolicy = class {
  constructor(props) {
    this.excludedTriageStates = new Set(props.excludedTriageStates);
    this.includeUnmappedFindings = props.includeUnmappedFindings;
    this.severityThreshold = props.severityThreshold;
  }
  shouldInclude(input) {
    if (severityOrder[input.severity] < severityOrder[this.severityThreshold]) {
      return false;
    }
    if (this.excludedTriageStates.has(input.triageState)) {
      return false;
    }
    if (input.resolution.affectedProjects.length > 0) {
      return true;
    }
    return this.includeUnmappedFindings && input.resolution.unmappedSboms.length > 0;
  }
  toJSON() {
    return {
      excludedTriageStates: Array.from(this.excludedTriageStates),
      includeUnmappedFindings: this.includeUnmappedFindings,
      severityThreshold: this.severityThreshold
    };
  }
};

// src/application/rollup/DailyRollupGenerator.ts
var DailyRollupGenerator = class {
  constructor(selectFindings, renderer, writer) {
    this.selectFindings = selectFindings;
    this.renderer = renderer;
    this.writer = writer;
  }
  async execute(input) {
    const findings = this.selectFindings.execute({
      affectedProjectsByVulnerabilityRef: input.affectedProjectsByVulnerabilityRef,
      policy: new DailyRollupPolicy({
        excludedTriageStates: input.settings.excludedTriageStates,
        includeUnmappedFindings: input.settings.includeUnmappedFindings,
        severityThreshold: input.settings.severityThreshold
      }),
      triageByCacheKey: input.triageByCacheKey,
      vulnerabilities: input.vulnerabilities
    });
    const document = this.renderer.render({
      date: input.date,
      findings
    });
    const written = await this.writer.write({
      date: input.date,
      document,
      folderPath: input.settings.folderPath
    });
    return {
      content: written.content,
      date: input.date,
      findingsCount: findings.length,
      path: written.path
    };
  }
};

// tests/application/rollup/DailyRollupGenerator.test.ts
var settings = {
  autoGenerateOnFirstSyncOfDay: false,
  excludedTriageStates: ["mitigated", "false_positive", "suppressed"],
  folderPath: "VulnDash Briefings",
  includeUnmappedFindings: true,
  lastAutoGeneratedOn: "",
  severityThreshold: "HIGH"
};
test("DailyRollupGenerator orchestrates selection, rendering, and writing", async () => {
  const findings = [];
  const calls = [];
  const selector = {
    execute: (input) => {
      calls.push("select");
      assert.equal(input.date, void 0);
      return findings;
    }
  };
  const rendered = {
    analystNotesHeading: "## Analyst Notes",
    analystNotesPlaceholder: "- Placeholder",
    managedSections: [],
    title: "# VulnDash Briefing 2026-04-18"
  };
  const renderer = {
    render: (input) => {
      calls.push("render");
      assert.equal(input.date, "2026-04-18");
      assert.equal(input.findings, findings);
      return rendered;
    }
  };
  const writer = {
    write: async (input) => {
      calls.push("write");
      assert.equal(input.date, "2026-04-18");
      assert.equal(input.document, rendered);
      assert.equal(input.folderPath, "VulnDash Briefings");
      return {
        content: "# VulnDash Briefing 2026-04-18",
        created: true,
        path: "VulnDash Briefings/VulnDash Briefing 2026-04-18.md"
      };
    }
  };
  const result = await new DailyRollupGenerator(selector, renderer, writer).execute({
    affectedProjectsByVulnerabilityRef: /* @__PURE__ */ new Map(),
    date: "2026-04-18",
    settings,
    triageByCacheKey: /* @__PURE__ */ new Map(),
    vulnerabilities: []
  });
  assert.deepEqual(calls, ["select", "render", "write"]);
  assert.equal(result.findingsCount, 0);
  assert.equal(result.path, "VulnDash Briefings/VulnDash Briefing 2026-04-18.md");
});
