import assert from 'node:assert/strict';
import test from 'node:test';
import {
  DEFAULT_CACHE_STORAGE,
  DEFAULT_COLUMN_VISIBILITY,
  DEFAULT_DAILY_ROLLUP_SETTINGS,
  DEFAULT_FEEDS,
  DEFAULT_OSV_ENDPOINT_URL,
  DEFAULT_OSV_MAX_BATCH_SIZE,
  DEFAULT_SETTINGS,
  DEFAULT_SYNC_CONTROLS,
  MAX_CONFIGURABLE_OSV_BATCH_SIZE,
  MAX_OSV_CONCURRENT_BATCHES,
  SETTINGS_VERSION,
  getDefaultOsvFeedConfig
} from '../../../src/application/use-cases/DefaultSettings';
import { BUILT_IN_FEEDS, FEED_TYPES } from '../../../src/domain/feeds/FeedTypes';
import { CLOSED_TRIAGE_STATES } from '../../../src/domain/triage/TriageState';

test('default settings constants preserve the existing built-in values', () => {
  assert.deepEqual(DEFAULT_COLUMN_VISIBILITY, {
    id: true,
    title: true,
    source: true,
    severity: true,
    cvssScore: true,
    publishedAt: true
  });
  assert.deepEqual(DEFAULT_CACHE_STORAGE, {
    hardCap: 5000,
    hydrateMaxItems: 1000,
    hydratePageSize: 200,
    pruneBatchSize: 250,
    ttlMs: 30 * 24 * 60 * 60 * 1000
  });
  assert.deepEqual(DEFAULT_DAILY_ROLLUP_SETTINGS, {
    folderPath: 'VulnDash Briefings',
    severityThreshold: 'HIGH',
    excludedTriageStates: [...CLOSED_TRIAGE_STATES],
    includeUnmappedFindings: true,
    autoGenerateOnFirstSyncOfDay: false,
    lastAutoGeneratedOn: ''
  });
  assert.deepEqual(DEFAULT_SYNC_CONTROLS, {
    maxPages: 10,
    maxItems: 500,
    retryCount: 3,
    backoffBaseMs: 1_000,
    overlapWindowMs: 180_000,
    bootstrapLookbackMs: 86_400_000,
    debugHttpMetadata: false
  });
  assert.equal(MAX_OSV_CONCURRENT_BATCHES, 8);
  assert.equal(DEFAULT_OSV_ENDPOINT_URL, 'https://api.osv.dev/v1/querybatch');
  assert.equal(DEFAULT_OSV_MAX_BATCH_SIZE, 1000);
  assert.equal(MAX_CONFIGURABLE_OSV_BATCH_SIZE, 10_000);
  assert.equal(SETTINGS_VERSION, 10);
});

test('default feeds remain stable and the OSV helper returns the built-in OSV feed', () => {
  assert.deepEqual(DEFAULT_FEEDS, [
    {
      id: BUILT_IN_FEEDS.NVD.id,
      name: BUILT_IN_FEEDS.NVD.name,
      type: FEED_TYPES.NVD,
      enabled: true,
      dateFilterType: 'modified'
    },
    {
      id: BUILT_IN_FEEDS.GITHUB_ADVISORY.id,
      name: BUILT_IN_FEEDS.GITHUB_ADVISORY.name,
      type: FEED_TYPES.GITHUB_ADVISORY,
      enabled: true
    },
    {
      id: BUILT_IN_FEEDS.OSV.id,
      name: BUILT_IN_FEEDS.OSV.name,
      type: FEED_TYPES.OSV,
      enabled: false,
      cacheTtlMs: 21_600_000,
      negativeCacheTtlMs: 3_600_000,
      requestTimeoutMs: 15_000,
      maxConcurrentBatches: 4,
      osvEndpointUrl: DEFAULT_OSV_ENDPOINT_URL,
      osvMaxBatchSize: DEFAULT_OSV_MAX_BATCH_SIZE
    }
  ]);

  assert.deepEqual(getDefaultOsvFeedConfig(), DEFAULT_FEEDS[2]);
});

test('default settings still compose the extracted constants without mutating values', () => {
  assert.equal(DEFAULT_SETTINGS.columnVisibility, DEFAULT_COLUMN_VISIBILITY);
  assert.equal(DEFAULT_SETTINGS.cacheStorage, DEFAULT_CACHE_STORAGE);
  assert.deepEqual(DEFAULT_SETTINGS.dailyRollup, DEFAULT_DAILY_ROLLUP_SETTINGS);
  assert.deepEqual(DEFAULT_SETTINGS.syncControls, DEFAULT_SYNC_CONTROLS);
  assert.notEqual(DEFAULT_SETTINGS.dailyRollup, DEFAULT_DAILY_ROLLUP_SETTINGS);
  assert.notEqual(DEFAULT_SETTINGS.syncControls, DEFAULT_SYNC_CONTROLS);
  assert.equal(DEFAULT_SETTINGS.settingsVersion, SETTINGS_VERSION);
  assert.deepEqual(DEFAULT_SETTINGS.feeds, DEFAULT_FEEDS);
  assert.notEqual(DEFAULT_SETTINGS.feeds, DEFAULT_FEEDS);
});
